      - name: Commit & Push known-tokens.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add known-tokens.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update known-tokens.json [auto]"
            git push
          fi
        continue-on-error: true
